export const INCREMENT_BREAK_LENGTH = "INCREMENT_BREAK_LENGTH";
export const INCREMENT_SESSION_LENGTH = "INCREMENT_SESSION_LENGTH";
export const DECREMENT_BREAK_LENGTH = "DECREMENT_BREAK_LENGTH";
export const DECREMENT_SESSION_LENGTH = "DECREMENT_SESSION_LENGTH";
export const TOGGLE_COUNTER = "TOGGLE_COUNTER";
export const DECREMENT_CURRENT_TIME = "DECREMENT_CURRENT_TIME";
export const RESET = "RESET";